debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: jgm
    password: jgm1234
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always

  data:
    rest:
      base-path: /api
      detection-strategy: annotated

logging:
  level:
    com.jgm.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.spi.BasicBinder: trace

